from pathlib import Path

CHECKPOINT_PATH = Path(__file__).parent / 'checkpoints' / 'base.ckpt'

RBS_INIT_BASE_SEQUENCES = [
    'TCTAGAGTTCACACAGGAAACCTACTAG',
    'TCTAGAGATTAAAGAGGAGAAATACTAG',
    'TCTAGAGTCACACAGGAAACCTACTAG',
    'TCTAGAGTCACACAGGAAAGTACTAG',
    'TCTAGAGTCACACAGGACTACTAG',
    'TCTAGAGAAAGAGGAGAAATACTAG',
    'TCTAGAGATTAAAGAGGAGAATACTAG',
    'TCTAGAGAAAGAGGGGAAATACTAG',
]
