name: "Set up Python"
description: "Set up Python environment for uv project"
inputs:
  uv_version:
    required: true
    description: "uv version"
  working_dir:
    required: true
    description: "pyproject.toml directory path"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ inputs.uv_version }}

    - name: Set up Python
      shell: bash
      run: | # .python-version file should be present in the working_dir
        uv python install
      working-directory: ${{ inputs.working_dir }}

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-extras
      working-directory: ${{ inputs.working_dir }}

    - name: Set up Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
