site_name: Synergetica
site_url: https://docs.synergetica/

nav:
  - Introduction: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Tutorial: getting-started/tutorial.md
  - Guides:
      - Circuit design: guides/circuit-design.md
      - Genetic simulation: guides/genetic-simulation.md
      - Sequence generation: guides/sequence-generation.md
      - Parts customization: guides/parts-customization.md

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  palette:
    scheme: default
    primary: custom
    accent: custom
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/khokao/synergetica

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/overrides/.icons

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
