site_name: MaGesty
site_url: https://MaGesty.org/MaGesty

nav:
  - Home: index.md
  - Getting Started:
    - Install : pages/getting_starts/install.md
    - Tutorial: pages/getting_starts/tutorial.md
  - Guide:
    - GUI circuit design: 
      - Design Circuit: pages/guide/gui/design.md
      - Parts: pages/guide/gui/parts.md
      - DSL: pages/guide/gui/dsl.md
    - Simulation: pages/guide/simulation.md
    - Seqence Generation: pages/guide/generation.md



theme:
  name: material
  logo: img/demo.svg
  favicon: img/demo2.png
  languages: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja
