name: Docker

on:
  push:
    branches:
      - main
    paths:
      - "services/**"
      - "!services/docs/**"
      - "!services/mkdocs.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: khokao
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./services
          file: ./services/Dockerfile
          push: true
          tags: khokao/synergetica:latest
          no-cache: true
