name: Docker build and push to Docker Hub

on:
  push:
    paths:
      - "services/**"
      - "!services/docs/**"
      - "!services/mkdocs.yml"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./services

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: khokao
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: khokao/synergetica:latest
