name: "GitHub Pages Deploy"
on:
  push:
    branches:
      - docs/init
    paths:
      - "docs/**"

permissions:
  contents: write

defaults:
  run:
    working-directory: ./docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: ./.github/composite/setup-python
        with:
          python_version: "3.12"
          poetry_version: "1.8"
          working_dir: docs

      - name: Deploy to GitHub Pages
        run: poetry run mkdocs gh-deploy --force
