name: "Document GitHub Pages Deploy"
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: write

defaults:
  run:
    working-directory: ./backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: ./.github/composite/setup-python
        with:
          python_version: "3.12"
          uv_version: "0.5.5"
          working_dir: backend      

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy -f ../docs/mkdocs.yml --force
