name: "Node biome check"

on:
  push:
    branches:
      - main
    paths:
      - "desktop/**"
      - "!desktop/src-tauri/**"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "desktop/**"
      - "!desktop/src-tauri/**"

permissions:
  contents: read
  checks: write
  pull-requests: write

defaults:
  run:
    working-directory: ./desktop

jobs:
  biome-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/composite/setup-node
        with:
          node_version: "21"
          working_dir: desktop

      # ref: https://github.com/mongolyy/reviewdog-action-biome/
      - name: biome check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx biome check . 2>&1 1>/dev/null |
          sed 's/ *$//' |
          awk 'BEGIN { RS=""; ORS="\n\n" } { if (index($0, "│") > 0) { print "  ```\n" $0 "\n  ```" } else { print $0 } }' |
          reviewdog \
            -efm="%-G%f ci ━%#" \
            -efm="%-G%f lint ━%#" \
            -efm="%-Gci ━%#" \
            -efm="%E%f:%l:%c %.%#" \
            -efm="%E%f %.%#" \
            -efm="%C" \
            -efm="%C  × %m" \
            -efm="%C  %m" \
            -efm="%-G%.%#" \
            -name="Biome check" \
            -reporter="github-pr-review" \
            -fail-on-error="true" \
            -filter-mode="nofilter" \
            -level="warning"
