name: "Node vitest"

on:
  push:
    branches:
      - main
    paths:
      - "desktop/**"
      - "!desktop/src-tauri/**"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "desktop/**"
      - "!desktop/src-tauri/**"

permissions:
  contents: read
  checks: write
  pull-requests: write

defaults:
  run:
    working-directory: ./desktop

jobs:
  vitest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/composite/setup-node
        with:
          node_version: "21"
          working_dir: desktop

      - name: vitest
        run: npm run coverage

      - name: Vitest coverage comment
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./desktop/coverage/coverage-summary.json
          json-final-path: ./desktop/coverage/coverage-final.json
          vite-config-path: ./desktop/vitest.config.mts
          file-coverage-mode: all
