name: "Python mypy"

on:
  push:
    branches:
      - main
    paths:
      - "python/**"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "python/**"

permissions:
  contents: read
  checks: write
  pull-requests: write

defaults:
  run:
    working-directory: ./python

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/composite/setup-python
        with:
          python_version: "3.12"
          poetry_version: "1.8"
          working_dir: python

      - name: mypy
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run mypy \
            | reviewdog -f="mypy" \
            -name="mypy" \
            -reporter="github-pr-review" \
            -fail-on-error="true" \
            -filter-mode="nofilter" \
            -level="warning"
